In [1]:
import numpy as np

In [5]:
L = np.random.random(100)
L

array([0.73566395, 0.85440837, 0.52184323, 0.95298247, 0.0359254 ,
       0.60962062, 0.21840108, 0.17967824, 0.82158181, 0.41783546,
       0.56809564, 0.24502989, 0.52053627, 0.54879874, 0.83054221,
       0.10257266, 0.5121343 , 0.04982618, 0.14896731, 0.51042411,
       0.32897892, 0.58482982, 0.18573336, 0.79563187, 0.89745851,
       0.18148008, 0.11537107, 0.01150696, 0.2635799 , 0.07889351,
       0.18579334, 0.6849955 , 0.92842567, 0.82574882, 0.0954875 ,
       0.93016613, 0.78295434, 0.57001716, 0.05266172, 0.26402692,
       0.7080368 , 0.57408068, 0.94918394, 0.26641404, 0.32264661,
       0.5808294 , 0.60388985, 0.80649918, 0.87855441, 0.44063181,
       0.23645273, 0.73719809, 0.95724157, 0.758456  , 0.33269539,
       0.3607315 , 0.35814274, 0.85143657, 0.2415451 , 0.07688103,
       0.47193468, 0.43733836, 0.70168795, 0.39848896, 0.93380241,
       0.34095274, 0.73539377, 0.33541619, 0.88125974, 0.99254322,
       0.46752603, 0.97343484, 0.43604753, 0.10614583, 0.85050

In [6]:
sum(L)

47.84268437353851

In [7]:
np.sum(L)

47.8426843735385

In [8]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

88 ms ± 2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
1.04 ms ± 27.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [9]:
min(big_array)

5.156684492746422e-07

In [10]:
max(big_array)

0.9999984641105022

In [11]:
print(big_array.min(), big_array.max(), big_array.sum())

5.156684492746422e-07 0.9999984641105022 500020.956908299


In [12]:
M = np.random.random((3, 4))
print(M)

[[0.66241655 0.38677663 0.47239448 0.59104034]
 [0.14470702 0.91567778 0.27280647 0.22116818]
 [0.07607089 0.06454175 0.05600453 0.07727332]]


In [13]:
M.sum()

3.9408779489419192

In [14]:
M.min(axis=0)

array([0.07607089, 0.06454175, 0.05600453, 0.07727332])

In [15]:
M.max(axis=1)

array([0.66241655, 0.91567778, 0.07727332])