In [2]:
import numpy as np

In [3]:
L= list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [5]:
print("x3 dim:",x3.ndim)
print("x3 shape: ",x3.shape)
print("x3 size: ",x3.size)

x3 dim: 3
x3 shape:  (3, 4, 5)
x3 size:  60


In [6]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [7]:
print("x3 data type: ",x3.dtype)

x3 data type:  int64


In [8]:
print('item size:',x3.itemsize,'bytes')
print('nbytes',x3.nbytes,'bytes')

item size: 8 bytes
nbytes 480 bytes


In [9]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
x1[0]

5

In [11]:
x1[-1]

9

In [12]:
x1[-x1.size]

5

In [13]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [14]:
x2[0,3]

4

In [15]:
x2[0,1] = 2

In [16]:
x2

array([[3, 2, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [17]:
x1[0] = .3

In [18]:
x1

array([0, 0, 3, 3, 7, 9])

In [19]:
x1[0] = 3.14

In [20]:
x1

array([3, 0, 3, 3, 7, 9])

In [21]:
x1?

Type:            ndarray
String form:     [3 0 3 3 7 9]
Length:          6
File:            ~/Documents/data-science/lib/python3.8/site-packages/numpy/__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape

In [22]:
x = np.arange(10)

In [23]:
x[:5]

array([0, 1, 2, 3, 4])

In [24]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[5:]

array([5, 6, 7, 8, 9])

In [26]:
x[4:7]

Error: Debugging while attached to a remote server is not currently supported.

In [32]:
x[::2]

array([0, 2, 4, 6, 8])

### printing every 2th element from array

In [28]:
x[2::]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

step terbalik jadinya reverse array

In [33]:
x[5::-1]

array([5, 4, 3, 2, 1, 0])

In [34]:
reversed_x = x[::-1]

In [35]:
reversed_x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [36]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x2

array([[3, 2, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [38]:
x2[:2, :3]

array([[3, 2, 2],
       [7, 6, 8]])

In [39]:
x2[:3, ::2]

array([[3, 2],
       [7, 8],
       [1, 7]])

In [40]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 2, 3]])

In [41]:
print(x2[:,0])

[3 7 1]


In [42]:
x2

array([[3, 2, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [43]:
print(x2[0,:])

[3 2 2 4]
