In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])
b = np.array([5,5,5])
a + b

array([6, 7, 8])

In [4]:
a + 5

array([6, 7, 8])

In [6]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
M + a

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [9]:
a = np.arange(3)
b = np.arange(3)[:,np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [10]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])