In [2]:
import numpy as np

In [3]:
L = [1,2,3,4,5]

In [4]:
type(L)

list

In [5]:
[type(item) for item in L]

[int, int, int, int, int]

In [6]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np

In [8]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [9]:
np.array([1,2,3.14])

array([1.  , 2.  , 3.14])

In [10]:
np.array([1,2,3,5],dtype='float32')

array([1., 2., 3., 5.], dtype=float32)

In [11]:
np.array([range(i,i+3) for i in[2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [13]:
np.ones((3,5), dtype="float")

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.zeros(10,dtype="int")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [18]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [20]:
np.linspace(0,1,17)

array([0.    , 0.0625, 0.125 , 0.1875, 0.25  , 0.3125, 0.375 , 0.4375,
       0.5   , 0.5625, 0.625 , 0.6875, 0.75  , 0.8125, 0.875 , 0.9375,
       1.    ])

In [23]:
np.random.random((3,3))

array([[0.09232549, 0.08852414, 0.01706157],
       [0.3462782 , 0.44904811, 0.83232371],
       [0.59363918, 0.51105722, 0.78748801]])

In [24]:
np.random.normal(0,1,(3,3))

array([[-0.02648437, -0.42825141, -0.9549754 ],
       [-1.22376008, -0.86934672,  0.40524227],
       [ 0.3316626 ,  0.59791052,  0.0846308 ]])

In [28]:
np.random.randint(0,10,(3,3))

array([[5, 8, 1],
       [5, 6, 9],
       [0, 6, 3]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])